---
deployment:
  tasks:
    - export DEPLOYPATH=/home/casualga/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css $DEPLOYPATH
    - /bin/cp images $DEPLOYPATH
    - /bin/cp test $DEPLOYPATH
    - /bin cp games $DEPLOYPATH